<a href="https://colab.research.google.com/github/aaroncdvd/HRBS-CA_Python_AI/blob/main/SamplePN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [>](https://developers.google.com/machine-learning/crash-course/fitter/graph) What is Learning!?

## Finding the Best Model by Minimizing the Errors

**How does the average error look during training?**
For instance, you are in a lake and must find the DEEPEST point, that's the global optimum. In other words, the 'best model'. 

You get into a BOAT and use an anchor and rope to measure the depth at different places. You compare each point with the LAST point you measured and make a graph. 

![PN](https://www.researchgate.net/profile/Md-Abu-Siddique-7/publication/330872299/figure/fig5/AS:722814940246018@1549343919385/Diagram-Showing-the-Cost-versus-Weight-Graph-In-Case-Of-Neural-Network-Gradient-Descent_Q640.jpg)

HINT: It is important to MINIMIZE the number of times you measure since each time you stop and measure takes a LOT of time.

**You need to decide how far you go between measurements and which direction you turn each time!**

**Where is the model the BEST FIT in this map, the DEEPEST POINT?**

[**What is the effect of the learning rate?**](https://developers.google.com/machine-learning/crash-course/fitter/graph)



## Class Example 'Error Lake'...
![PN](https://cdn3.volusion.com/ckwhr.vgayx/v/vspfiles/photos/CRTR-D1S-3.jpg?v-cache=1483985255)

## Real World Problem 'Error Lakes' look like this...
![](https://cdn3.volusion.com/ckwhr.vgayx/v/vspfiles/photos/WIKE-D4L-2.jpg?v-cache=1483617506)

# [>](https://analyticsindiamag.com/perceptron-is-the-only-neural-network-without-any-hidden-layer/) Sample Perceptron 

[Click This Link For Sample Perceptron on Google Sheets](https://docs.google.com/spreadsheets/d/1gWQugoCEZTMPTZ_LyanFjuPo_GbG-r4-ZRSBLjVPlO0/edit#gid=0)



![PN](https://miro.medium.com/max/12840/1*v88ySSMr7JLaIBjwr4chTw.jpeg)


##How does this compare with the Sample NN (Neural Network) from the last class?

![](https://miro.medium.com/max/1018/1*fW1kWWa1HGosROKkpjzFQw.png)

## Sample Perceptron Code

In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[0, 1, 0], # input data (excel column A-C)
                   [0, 1, 1],
                   [0, 0, 0],
                   [1, 0, 0],
                   [1, 1, 1],
                   [1, 0, 1]])
outputs = np.array([[0], [0], [0], [1], [1], [1]]) # output data (Google Sheet column E)

In [ ]:
learning_rate=.01 # Set learning_rate, choose 1 : 1000,100,10,1,0,.01,.001,.0001
epochs=4 # Set epochs

In [ ]:
rand = np.random.RandomState(5) # Random state can be changed
weights = rand.normal(loc=0.0, scale=0.01, size=1 +  inputs.shape[1]) # Create initial weights
weights # Google Sheet columns G-J

array([ 0.00441227, -0.0033087 ,  0.02430771, -0.00252092])

In [ ]:
error_history=[]
for _ in range(epochs):
  errors_=[]
  for input, output in zip(inputs, outputs):
    
    z = np.dot(input, weights[1:]) + weights[0]
    predict = np.where(z >= 0, 1, 0)
    
    error = output - predict
    
    update = learning_rate * error
    weights[1:] += update * input
    weights[0] += update

    errors_.append(error)
  error_history.append(np.average(np.abs(errors_)))
  print(weights)
print(error_history)

[ 0.00441227  0.0166913   0.01430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[0.6666666666666666, 0.16666666666666666, 0.0, 0.0]


In [ ]:
error_history=[] # Create new error_history
for _ in range(epochs): # Loop through epochs
  errors_=[] # Create new errors_ list for every epoch
  for input, output in zip(inputs, outputs): # Loop through inputs (1 per Google Sheet row in columns A-T)
    # Calculate predicted output
    z = np.dot(input, weights[1:]) + weights[0] # Calculate z  (Google Sheet column L)
    predict = np.where(z >= 0, 1, 0) # Calculate algorithm's prediction (Google Sheet column M)
    # Calculate predicted output Error
    error = output - predict # Calculate algorithm's error (Google Sheet column N)
    # Apply 'learning' and update weights and bias
    update = learning_rate * error # Calculate necessary update to weights (Google Sheet column O)
    weights[1:] += update * input # Apply update to input weights, one for each input column (Google Sheet columns R-T)
    weights[0] += update # Apply update to bias weight (Google Sheet column Q)
    # Log the error for error_history below
    errors_.append(error) # Create list of errors (Google Sheet column N)
  error_history.append(np.average(np.abs(errors_))) # Average list of errors for each epoch (Google Sheet column N, rows 9,18,27,36)
  print(weights)
print(error_history)

[ 0.00441227  0.0166913   0.01430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[-0.00558773  0.0166913   0.00430771 -0.00252092]
[0.6666666666666666, 0.16666666666666666, 0.0, 0.0]


In [ ]:
class Perceptron(object):
  def __init__(self, learning_rate=0.01, n_iter=100, random_state=1):
    self.learning_rate = learning_rate
    self.n_iter = n_iter
    self.random_state = random_state


  def fit(self, X, y):
    rand = np.random.RandomState(self.random_state)
    self.weights = rand.normal(loc=0.0, scale=0.01, size=1 +  X.shape[1])
    self.errors_ = []

  for _ in range(self.n_iter):
      errors = 0
      for x, target in zip(X, y):
        update = self.learning_rate * (target - self.predict(x))
        self.weights[1:] += update * x
        self.weights[0] += update
        errors += int(update != 0.0)
        self.errors_.append(errors)
      return self

  def net_input(self, X):
    z = np.dot(X, self.weights[1:]) + self.weights[0]
    return z

  def predict(self, X):
    return np.where(self.net_input(X) >= 0, 1, -1)